name: PR Validation

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_commit_messages:
    if: false
    name: check conventinal commit compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # pick the pr HEAD instead of the merge commit
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Check compliance
        run: devenv tasks run check:conventional-commit

  check_code_style:
    if: false
    name: check source code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # pick the pr HEAD instead of the merge commit
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Check formatting
        run: devenv tasks run check:code-lint

  check_tests:
    name: check tests
    needs:
      - check_commit_messages
      - check_code_style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # pick the pr HEAD instead of the merge commit
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Run Tests
        run: devenv tasks run check:fast-tests
      - name: Generate coverage report
        run: devenv tasks run check:coverage-report
      - name: Publish coverage report
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  check_package_build:
    if: false
    name: Check that package builds
    needs: check_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo shallowly
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # pick the pr HEAD instead of the merge commit
      - name: Preparing devenv
        uses: ./.github/actions/prepare-devenv
      - name: Build package
        run: devenv tasks run package:build

  build_docs_preview:
    if: false
    name: Check that documentation build
    needs: check_package_build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: checkout repo shallowly
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }} # pick the pr HEAD instead of the merge commit
      - name: prepare devenv
        uses: ./.github/actions/prepare-devenv
      - name: run docs build check
        shell: devenv shell bash -- -e {0}
        run: |
          devenv tasks run docs:single-page
          nix run nixpkgs#monolith -- build/docs/index.html > build/docs/single_page.html
      - name: Upload docs preview
        uses: actions/upload-artifact@v6
        id: artifact-upload
        with:
          name: docs-preview
          path: build/docs/single_page.html
          retention-days: 7
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: docs-preview
          message: |
            📚 Documentation preview has been built and attached as an artifact.

            [Download Documentation Preview](${{ steps.artifact-upload.outputs.artifact-url }})

            You can also find it in the "Artifacts" section of this workflow run.
