name: Build and Release Python Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_package:
    if: true
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Prepare Devenv environment
        uses: ./.github/actions/prepare-devenv
      - name: Build docs
        run: devenv tasks run "package:build"
      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  github-release:
    if: false
    name: Sign the Python 🐍 distribution 📦 with Sigstore and upload them to GitHub Release
    runs-on: ubuntu-latest
    needs: build_package
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: release-dists
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
      - name: create release
        id: release
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto
          git-user: "Intelligent Embedded Systems @ UDE"
          git-user-email: "noreply@ies.uni-due.de"
      - name: generate changelog
        run: |
          cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md
      - name: upload release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
          files: ./dist/**
